### ISSUE TITLE
pg dependency update needed

### ISSUE THREAD

**Issue by yentsun** [dmitriiabramov/node-sql-migrations#1]
I tried to run a migration on Node `v6.5.0` and was getting `ERROR: { error: password authentication failed for user ...`. The password was actually correct so it was very confusing.

It costed me substantial time to dig the code and google to find a similar issue https://github.com/strongloop/loopback-connector-postgresql/issues/138

After updating `pg` to  `4.5.5` the migrations finally worked. I'm making a pull request.

**Comment by yentsun** [comment]
@dmitriiabramov thanks for the merge, would you care to publish the update @ npm registry?

**Comment by boujeepossum** [comment]
@yentsun yeah! just published it!
thank you!

**Comment by Surbhi-sharma1** [comment]
how to update it?
